image: mcr.microsoft.com/dotnet/core/sdk:3.1

# Named pipes temporary hosting for agent:
# https://docs.google.com/uc?export=download&id=1GfkHkjbZ30IONYVUGuY90hEtx-8Uw3Vx
# Original URL format for agent artifact:
# http://s3.amazonaws.com/dsd6-staging/windows/agent7/buildpack/agent-binaries-7.22.1-1-x86_64.zip

# Named pipes temporary hosting for windows tracer home:
# https://docs.google.com/uc?export=download&id=1XkDjL24sIc5gycpieYUFXfqHVLtRB3e5
# Original URL format for windows tracer home:
# https://github.com/DataDog/dd-trace-dotnet/releases/download/v1.21.1/windows-tracer-home.zip

variables:
  AGENT_DOWNLOAD_URL: "https://docs.google.com/uc?export=download&id=1GfkHkjbZ30IONYVUGuY90hEtx-8Uw3Vx" 
  TRACER_DOWNLOAD_URL: "https://docs.google.com/uc?export=download&id=1XkDjL24sIc5gycpieYUFXfqHVLtRB3e5"
  TRACER_CONTENT_DIR: $CI_PROJECT_DIR/content/Tracer
  AGENT_CONTENT_DIR: $CI_PROJECT_DIR/content/Agent

create-site-extension-package:
  tags: [ "runner:main", "size:2xlarge" ]
  script:
    - echo "Installing dependencies"
    - apt-get update
    - apt-get install unzip
    - echo "Downloading agent from ${AGENT_DOWNLOAD_URL}"
    - wget -O agent.zip $AGENT_DOWNLOAD_URL
    - unzip agent.zip -d agent-extract
    - echo "Downloading tracer from ${TRACER_DOWNLOAD_URL}"
    - wget -O tracer.zip $TRACER_DOWNLOAD_URL
    - unzip tracer.zip -d tracer-extract
    - echo "Moving agent executables and tracer binaries"
    - mkdir $TRACER_CONTENT_DIR
    - mv -v tracer-extract/* $TRACER_CONTENT_DIR
    - mv agent-extract/bin/agent/dogstatsd.exe $AGENT_CONTENT_DIR
    - mv agent-extract/bin/agent/trace-agent.exe agent-extract/bin/agent/datadog-trace-agent.exe
    - mv agent-extract/bin/agent/datadog-trace-agent.exe $AGENT_CONTENT_DIR
    - echo "Creating nuget package"
    - echo "Packing nuspec file via arcane roundabout csproj process"
    - dotnet pack Datadog.AzureAppServices.csproj -p:NoBuild=true -p:NoDefaultExcludes=true -o package
  artifacts:
    expire_in: 2 weeks
    paths:
      - package
